name: Savor each second
favicon: null
layout_spectrum: 0.5483871
typography_spectrum: 0.765233
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: "Savor what's special"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#9CA093'
    - '#1D1F20'
    - '#4D4D4D'
    - '#848A7F'
  brandStrength: 0.5663083
  lightness: 0.6935484
  saturation: 0.3315412
  rhythmicContrast: 0.5555556
purpose: []
