name: Canlis Treatment
favicon: null
layout_spectrum: 0.23762
typography_spectrum: 0.95904
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Canlis
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#080c12'
    - '#8c9068'
    - '#5b5739'
    - '#3d3c28'
    - '#acb28e'
  brandStrength: 0.9375
  lightness: 0.4375
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
